//Numbers (Math.())
const x = 8.5533;
//math.floor() --> arredonda para baixo
console.log(Math.floor(x));
//math.ceil() --> arrendonda para cima
console.log(Math.ceil(x));
//Math.trunc() --> apenas mostra a parte inteira
console.log(Math.trunc(x));
//Math.sqrt() --> raiz quadrada
console.log(Math.sqrt(x));
//Math.pow(x,y) --> eleva um numero a outro
console.log(Math.pow(2,3)); //2 elevado a 3
//toFixed() --> Quantidade de decimais desejados
console.log(x.toFixed(2));
